version: 2
jobs:
  build:
    docker:
    - image: circleci/node:9.11
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          - npm-cache-{{ .Branch }}
          - npm-cache-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
      # run tests!
      - run: yarn build

  test:
    docker:
    - image: circleci/node:9.11
    steps:
      - checkout
      - run: yarn
      - run: yarn test

  deploy:
    docker:
    - image: circleci/node:9.11
    steps:
      - checkout
      - run: sudo npm install --global --unsafe-perm now
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              now --token $NOW_TOKEN --team yfd -e CONTENTFUL_SPACE_ID=${PRODUCTION_CONTENTFUL_SPACE_ID} -e CONTENTFUL_ACCESS_TOKEN=${PRODUCTION_CONTENTFUL_ACCESS_TOKEN}
              now --token $NOW_TOKEN --team yfd --local-config .now/now.production.json
              now --token $NOW_TOKEN --team yfd --local-config .now/now.production.json alias
            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
              now --token $NOW_TOKEN --team yfd -e CONTENTFUL_SPACE_ID=${STAGING_CONTENTFUL_SPACE_ID} -e CONTENTFUL_ACCESS_TOKEN=${STAGING_CONTENTFUL_ACCESS_TOKEN}
              now --token $NOW_TOKEN --team yfd --local-config .now/now.staging.json
              now --token $NOW_TOKEN --team yfd --local-config .now/now.staging.json alias
            else
              echo "Dry run as the current branch is ${CIRCLE_BRANCH}"
            fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - development