version: 2
jobs:
  build:
    docker:
    - image: circleci/node:9.11
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          - npm-cache-{{ .Branch }}
          - npm-cache-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
      # run tests!
      - run: yarn build

  test:
    docker:
    - image: circleci/node:9.11
    working_directory: ~/repo
    steps:
      - run: yarn
      - run: yarn test

  deploy:
    docker:
    - image: circleci/node:9.11
    working_directory: ~/repo
    branches:
      only:
        - master
        - development
    steps:
      - run: sudo npm install --global --unsafe-perm now
      - deploy:
        name: deploy
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            now --token $NOW_TOKEN --local-config .now/now.production.json
            now --token $NOW_TOKEN --local-config .now/now.production.json alias
          elif [ "${CIRCLE_BRANCH}" == "development" ]; then
            now --token $NOW_TOKEN --local-config .now/now.staging.json
            now --token $NOW_TOKEN --local-config .now/now.staging.json alias
          else
            echo "FUFU"
          fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires: build
      - deploy:
          requires: test